import {
  Category,
  Product,
  Order,
  CustomerAddress,
  UserProfile,
  StoreProfile,
  StoreSettings,
  ContactMessage,
  InventoryHistory,
  PaymentTransaction,
  AdminActivityLog,
  CustomerNote,
  Coupon,
} from './types';

export const INITIAL_STORE_PROFILE: StoreProfile = {
  id: '00000000-0000-0000-0000-000000000001',
  store_name: 'SR Jewellery Collections',
  logo_url: '/logo.jpg',
  tagline: 'Timeless Elegance & Royal Heritage Jewellery',
  description: 'Discover hand-crafted Kundan, Polki, Gold & Diamond Jewellery designed for modern royalty. Every piece reflects Indian heritage, fine craftsmanship, and luxury.',
  email: 'contact@srjewellerycollections.com',
  phone: '+91 8790522579',
  whatsapp: '+918790522579',
  address: '108 Royal Heritage Galleria, MG Road',
  city: 'Hyderabad',
  state: 'Telangana',
  pincode: '500001',
  map_url: 'https://maps.google.com/?q=Hyderabad',
  instagram_url: 'https://instagram.com/srjewellery',
  facebook_url: 'https://facebook.com/srjewellery',
  youtube_url: 'https://youtube.com/srjewellery',
  business_hours: 'Mon - Sat: 10:30 AM - 8:30 PM | Sun: Closed',
  upi_id: 'sushmitha.admin@okaxis',
  updated_at: '2024-01-01T00:00:00.000Z',
};

export const INITIAL_STORE_SETTINGS: StoreSettings = {
  id: '00000000-0000-0000-0000-000000000002',
  currency: 'INR',
  currency_symbol: '₹',
  shipping_fee: 99,
  free_shipping_threshold: 1999,
  cod_enabled: true,
  min_cod_value: 299,
  max_cod_value: 25000,
  upi_enabled: true,
  tax_percentage: 3,
  auto_confirm_orders: false,
  low_stock_threshold_global: 5,
  allow_cancellation: true,
  allow_returns: true,
  razorpay_test_mode: true,
  updated_at: '2024-01-01T00:00:00.000Z',
};

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Earrings',
    slug: 'earrings',
    description: 'Traditional Jhumkas, Chandbalis, Studs & Danglers in Gold and Polki',
    image_url: '/images/pink_ruby_jhumka_earrings.jpg',
  },
  {
    id: 'cat-2',
    name: 'Necklaces & Sets',
    slug: 'necklaces',
    description: 'Royal Kundan Chokers, Antique Gold Sets & Temple Necklaces',
    image_url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600',
  },
  {
    id: 'cat-3',
    name: 'Rings',
    slug: 'rings',
    description: 'Solitaires, Cocktail Rings & Traditional Gold Band Rings',
    image_url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600',
  },
  {
    id: 'cat-4',
    name: 'Bangles & Bracelets',
    slug: 'bangles',
    description: 'Heritage Kada Bangles, Diamond Tennis Bracelets & Meenakari Bangles',
    image_url: 'https://images.unsplash.com/photo-1611591475285-a36adaf961e0?w=600',
  },
  {
    id: 'cat-5',
    name: 'Maang Tikka',
    slug: 'maang-tikka',
    description: 'Bridal Head Pieces, Passa & Statement Kundan Tikkas',
    image_url: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-ear-1',
    name: 'Dhara Royal Pink Ruby & Polki Jhumka Earrings',
    sku: 'SRJ-JHM-101',
    slug: 'dhara-royal-pink-ruby-polki-jhumka-earrings',
    category_id: 'cat-1',
    category_name: 'Earrings',
    description: 'Handcrafted Dhara signature royal pink ruby stone & polki diamond studded traditional gold plated Jhumka earrings.',
    original_price: 250,
    selling_price: 160,
    discount_percentage: 36,
    stock_quantity: 20,
    low_stock_threshold: 3,
    material: '22K Gold Plated Alloy',
    stone_type: 'Ruby Pink Gemstones & CZ Polki',
    colour: 'Gold & Pink Ruby',
    weight: '38g',
    size: 'Standard Jhumka',
    dimensions: '6.5cm Length x 3cm Width',
    care_instructions: 'Keep away from perfumes, water, and direct moisture.',
    shipping_info: 'Insured Express Shipping in 2-4 business days.',
    return_info: '7-Day Easy Returns & Exchanges.',
    tags: ['Earrings', 'Jhumka', 'Ruby', 'Dhara', 'Polki'],
    is_featured: true,
    is_new_arrival: true,
    is_best_seller: true,
    is_active: true,
    images: ['/images/pink_ruby_jhumka_earrings.jpg'],
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'prod-ear-2',
    name: 'Laher Cyan Blue Lotus Heritage Jhumka Earrings',
    sku: 'SRJ-JHM-102',
    slug: 'laher-cyan-blue-lotus-heritage-jhumka-earrings',
    category_id: 'cat-1',
    category_name: 'Earrings',
    description: 'Exclusive Laher handcrafted cyan blue enamel lotus motif silver oxide Jhumka earrings with beaded drops.',
    original_price: 250,
    selling_price: 160,
    discount_percentage: 36,
    stock_quantity: 20,
    low_stock_threshold: 3,
    material: 'Silver Oxide Plated Metal',
    stone_type: 'Cyan Blue Enamel & Crystal Beads',
    colour: 'Silver & Cyan Blue',
    weight: '32g',
    size: 'Medium Jhumka',
    dimensions: '6cm Length x 2.8cm Width',
    care_instructions: 'Store in airtight box after use.',
    shipping_info: 'Insured Express Shipping in 2-4 business days.',
    return_info: '7-Day Easy Returns & Exchanges.',
    tags: ['Earrings', 'Lotus', 'Jhumka', 'Blue', 'Silver'],
    is_featured: true,
    is_new_arrival: true,
    is_best_seller: true,
    is_active: true,
    images: ['/images/earrings_blue_lotus.jpg'],
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'prod-ear-3',
    name: 'Dhara Emerald Green Gemstone Jhumka Earrings',
    sku: 'SRJ-JHM-103',
    slug: 'dhara-emerald-green-gemstone-jhumka-earrings',
    category_id: 'cat-1',
    category_name: 'Earrings',
    description: 'Dhara royal collection antique gold finish emerald green cabochon gemstone studded Jhumka earrings.',
    original_price: 250,
    selling_price: 160,
    discount_percentage: 36,
    stock_quantity: 20,
    low_stock_threshold: 3,
    material: 'Antique Gold Plated Brass',
    stone_type: 'Emerald Green Gemstones & Polki',
    colour: 'Antique Gold & Emerald Green',
    weight: '35g',
    size: 'Standard Jhumka',
    dimensions: '6.2cm Length x 3cm Width',
    care_instructions: 'Clean with dry soft cloth.',
    shipping_info: 'Insured Express Shipping in 2-4 business days.',
    return_info: '7-Day Easy Returns & Exchanges.',
    tags: ['Earrings', 'Jhumka', 'Emerald', 'Dhara', 'Green'],
    is_featured: true,
    is_new_arrival: true,
    is_best_seller: true,
    is_active: true,
    images: ['/images/earrings_emerald_dhara.jpg'],
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'prod-ear-4',
    name: 'AJ Art Silver Emerald Chandbali Statement Earrings',
    sku: 'SRJ-CHND-104',
    slug: 'aj-art-silver-emerald-chandbali-statement-earrings',
    category_id: 'cat-1',
    category_name: 'Earrings',
    description: 'Royal AJ Art designer silver finish emerald green stone & CZ diamond cluster traditional Chandbali earrings.',
    original_price: 250,
    selling_price: 160,
    discount_percentage: 36,
    stock_quantity: 20,
    low_stock_threshold: 3,
    material: 'Silver Plated Designer Metal',
    stone_type: 'Emerald Green & CZ Diamonds',
    colour: 'Silver & Emerald Green',
    weight: '42g',
    size: 'Large Chandbali',
    dimensions: '7.5cm Length x 4cm Width',
    care_instructions: 'Keep away from direct heat and water.',
    shipping_info: 'Insured Express Shipping in 2-4 business days.',
    return_info: '7-Day Easy Returns & Exchanges.',
    tags: ['Earrings', 'Chandbali', 'Emerald', 'Silver', 'Bridal'],
    is_featured: true,
    is_new_arrival: true,
    is_best_seller: true,
    is_active: true,
    images: ['/images/earrings_silver_emerald.jpg'],
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'prod-ear-5',
    name: 'Royal Silver Ruby Pink Chandbali Statement Earrings',
    sku: 'SRJ-CHND-105',
    slug: 'royal-silver-ruby-pink-chandbali-statement-earrings',
    category_id: 'cat-1',
    category_name: 'Earrings',
    description: 'Breathtaking silver polish ruby pink stone & mirror polki embellished crescent Chandbali earrings.',
    original_price: 250,
    selling_price: 160,
    discount_percentage: 36,
    stock_quantity: 20,
    low_stock_threshold: 3,
    material: 'Silver Plated Alloy',
    stone_type: 'Ruby Pink & Polki CZ Stones',
    colour: 'Silver & Ruby Pink',
    weight: '40g',
    size: 'Large Chandbali',
    dimensions: '7.2cm Length x 3.8cm Width',
    care_instructions: 'Store safely in jewellery pouch.',
    shipping_info: 'Insured Express Shipping in 2-4 business days.',
    return_info: '7-Day Easy Returns & Exchanges.',
    tags: ['Earrings', 'Chandbali', 'Ruby', 'Silver'],
    is_featured: true,
    is_new_arrival: true,
    is_best_seller: true,
    is_active: true,
    images: ['/images/earrings_silver_ruby.jpg'],
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'prod-ear-6',
    name: 'Dhara Golden Sunshine Yellow Floral Jhumka Earrings',
    sku: 'SRJ-JHM-106',
    slug: 'dhara-golden-sunshine-yellow-floral-jhumka-earrings',
    category_id: 'cat-1',
    category_name: 'Earrings',
    description: 'Vibrant Dhara floral motif sunshine yellow cabochon gemstone & CZ diamond studded silver polish Jhumka earrings with beaded drops.',
    original_price: 250,
    selling_price: 160,
    discount_percentage: 36,
    stock_quantity: 20,
    low_stock_threshold: 3,
    material: 'Silver Polish Premium Alloy',
    stone_type: 'Yellow Gemstones & CZ Diamonds',
    colour: 'Silver & Sunshine Yellow',
    weight: '34g',
    size: 'Medium Jhumka',
    dimensions: '6.2cm Length x 2.9cm Width',
    care_instructions: 'Keep away from perfumes, water, and direct moisture.',
    shipping_info: 'Insured Express Shipping in 2-4 business days.',
    return_info: '7-Day Easy Returns & Exchanges.',
    tags: ['Earrings', 'Jhumka', 'Yellow', 'Dhara', 'Festive'],
    is_featured: true,
    is_new_arrival: true,
    is_best_seller: true,
    is_active: true,
    images: ['/images/earrings_dhara_yellow.jpg'],
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'prod-ear-7',
    name: 'Royal Sky Blue Gemstone Chandbali Statement Earrings',
    sku: 'SRJ-CHND-107',
    slug: 'royal-sky-blue-gemstone-chandbali-statement-earrings',
    category_id: 'cat-1',
    category_name: 'Earrings',
    description: 'Exquisite silver finish sky blue turquoise oval gemstone & floral polki diamond cluster crescent Chandbali earrings.',
    original_price: 250,
    selling_price: 160,
    discount_percentage: 36,
    stock_quantity: 20,
    low_stock_threshold: 3,
    material: 'Silver Finish Designer Alloy',
    stone_type: 'Sky Blue Turqoise & Mirror CZ Stones',
    colour: 'Silver & Sky Blue',
    weight: '41g',
    size: 'Large Chandbali',
    dimensions: '7.4cm Length x 3.9cm Width',
    care_instructions: 'Store in soft dry cloth box.',
    shipping_info: 'Insured Express Shipping in 2-4 business days.',
    return_info: '7-Day Easy Returns & Exchanges.',
    tags: ['Earrings', 'Chandbali', 'Blue', 'Sky Blue', 'Bridal'],
    is_featured: true,
    is_new_arrival: true,
    is_best_seller: true,
    is_active: true,
    images: ['/images/earrings_sky_blue_chandbali.jpg'],
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'prod-ear-8',
    name: 'Laher Deep Royal Blue Lotus Enamel Jhumka Earrings',
    sku: 'SRJ-JHM-108',
    slug: 'laher-deep-royal-blue-lotus-enamel-jhumka-earrings',
    category_id: 'cat-1',
    category_name: 'Earrings',
    description: 'Heritage Laher royal blue enamel lotus motif silver oxide Jhumka earrings with deep blue crystal bead drops.',
    original_price: 250,
    selling_price: 160,
    discount_percentage: 36,
    stock_quantity: 20,
    low_stock_threshold: 3,
    material: 'Silver Oxide Finish Metal',
    stone_type: 'Royal Blue Enamel & Crystal Beads',
    colour: 'Silver & Royal Blue',
    weight: '33g',
    size: 'Standard Jhumka',
    dimensions: '6.1cm Length x 2.8cm Width',
    care_instructions: 'Keep away from moisture and direct chemical sprays.',
    shipping_info: 'Insured Express Shipping in 2-4 business days.',
    return_info: '7-Day Easy Returns & Exchanges.',
    tags: ['Earrings', 'Lotus', 'Jhumka', 'Royal Blue', 'Laher'],
    is_featured: true,
    is_new_arrival: true,
    is_best_seller: true,
    is_active: true,
    images: ['/images/earrings_laher_royal_blue.jpg'],
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'prod-ear-9',
    name: 'AJ Art Emerald Green Heritage Crescent Chandbali Earrings',
    sku: 'SRJ-CHND-109',
    slug: 'aj-art-emerald-green-heritage-crescent-chandbali-earrings',
    category_id: 'cat-1',
    category_name: 'Earrings',
    description: 'AJ Art designer silver polish emerald green stone & sparkling CZ diamond flower cluster traditional Chandbali earrings.',
    original_price: 250,
    selling_price: 160,
    discount_percentage: 36,
    stock_quantity: 20,
    low_stock_threshold: 3,
    material: 'Silver Plated AJ Art Alloy',
    stone_type: 'Emerald Green & Polki Diamonds',
    colour: 'Silver & Emerald Green',
    weight: '43g',
    size: 'Large Chandbali',
    dimensions: '7.6cm Length x 4.1cm Width',
    care_instructions: 'Store in dry airtight pouch.',
    shipping_info: 'Insured Express Shipping in 2-4 business days.',
    return_info: '7-Day Easy Returns & Exchanges.',
    tags: ['Earrings', 'Chandbali', 'Emerald', 'AJ Art', 'Green'],
    is_featured: true,
    is_new_arrival: true,
    is_best_seller: true,
    is_active: true,
    images: ['/images/earrings_aj_emerald_chandbali.jpg'],
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'prod-ear-10',
    name: 'Laher Royal Magenta Pink Lotus Enamel Jhumka Earrings',
    sku: 'SRJ-JHM-110',
    slug: 'laher-royal-magenta-pink-lotus-enamel-jhumka-earrings',
    category_id: 'cat-1',
    category_name: 'Earrings',
    description: 'Gorgeous Laher handcrafted royal magenta pink enamel lotus double-tier silver oxide Jhumka earrings with pink bead drops.',
    original_price: 250,
    selling_price: 160,
    discount_percentage: 36,
    stock_quantity: 20,
    low_stock_threshold: 3,
    material: 'Silver Oxide Metal',
    stone_type: 'Magenta Pink Enamel & Crystal Beads',
    colour: 'Silver & Magenta Pink',
    weight: '33g',
    size: 'Standard Jhumka',
    dimensions: '6.2cm Length x 2.8cm Width',
    care_instructions: 'Keep away from perfumes and store in dry pouch.',
    shipping_info: 'Insured Express Shipping in 2-4 business days.',
    return_info: '7-Day Easy Returns & Exchanges.',
    tags: ['Earrings', 'Lotus', 'Jhumka', 'Pink', 'Magenta'],
    is_featured: true,
    is_new_arrival: true,
    is_best_seller: true,
    is_active: true,
    images: ['/images/earrings_laher_magenta_pink.jpg'],
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'prod-ear-11',
    name: 'Laher Emerald Green Lotus Enamel Jhumka Earrings',
    sku: 'SRJ-JHM-111',
    slug: 'laher-emerald-green-lotus-enamel-jhumka-earrings',
    category_id: 'cat-1',
    category_name: 'Earrings',
    description: 'Vibrant Laher emerald green enamel lotus double-tier silver oxide Jhumka earrings with green crystal bead drops.',
    original_price: 250,
    selling_price: 160,
    discount_percentage: 36,
    stock_quantity: 20,
    low_stock_threshold: 3,
    material: 'Silver Oxide Metal',
    stone_type: 'Emerald Green Enamel & Crystal Beads',
    colour: 'Silver & Emerald Green',
    weight: '33g',
    size: 'Standard Jhumka',
    dimensions: '6.2cm Length x 2.8cm Width',
    care_instructions: 'Keep away from moisture and direct chemical sprays.',
    shipping_info: 'Insured Express Shipping in 2-4 business days.',
    return_info: '7-Day Easy Returns & Exchanges.',
    tags: ['Earrings', 'Lotus', 'Jhumka', 'Emerald', 'Green'],
    is_featured: true,
    is_new_arrival: true,
    is_best_seller: true,
    is_active: true,
    images: ['/images/earrings_emerald_lotus_jhumka.jpg'],
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'prod-ear-12',
    name: 'Laher Soft Baby Pink Lotus Enamel Jhumka Earrings',
    sku: 'SRJ-JHM-112',
    slug: 'laher-soft-baby-pink-lotus-enamel-jhumka-earrings',
    category_id: 'cat-1',
    category_name: 'Earrings',
    description: 'Delicate Laher pastel baby pink enamel lotus motif silver oxide Jhumka earrings with pink crystal bead drops.',
    original_price: 250,
    selling_price: 160,
    discount_percentage: 36,
    stock_quantity: 20,
    low_stock_threshold: 3,
    material: 'Silver Oxide Finish Metal',
    stone_type: 'Baby Pink Enamel & Crystal Beads',
    colour: 'Silver & Baby Pink',
    weight: '32g',
    size: 'Standard Jhumka',
    dimensions: '6.1cm Length x 2.8cm Width',
    care_instructions: 'Store in a dry cloth pouch after use.',
    shipping_info: 'Insured Express Shipping in 2-4 business days.',
    return_info: '7-Day Easy Returns & Exchanges.',
    tags: ['Earrings', 'Lotus', 'Jhumka', 'Pink', 'Baby Pink'],
    is_featured: true,
    is_new_arrival: true,
    is_best_seller: true,
    is_active: true,
    images: ['/images/earrings_baby_pink_lotus_jhumka.png'],
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'prod-ear-13',
    name: 'Laher Teal Sea Green Lotus Enamel Jhumka Earrings',
    sku: 'SRJ-JHM-113',
    slug: 'laher-teal-sea-green-lotus-enamel-jhumka-earrings',
    category_id: 'cat-1',
    category_name: 'Earrings',
    description: 'Refreshing Laher teal sea green enamel lotus motif silver oxide Jhumka earrings with matching bead drops.',
    original_price: 250,
    selling_price: 160,
    discount_percentage: 36,
    stock_quantity: 20,
    low_stock_threshold: 3,
    material: 'Silver Oxide Metal',
    stone_type: 'Teal Green Enamel & Crystal Beads',
    colour: 'Silver & Teal Green',
    weight: '33g',
    size: 'Standard Jhumka',
    dimensions: '6.2cm Length x 2.8cm Width',
    care_instructions: 'Keep away from direct heat and water.',
    shipping_info: 'Insured Express Shipping in 2-4 business days.',
    return_info: '7-Day Easy Returns & Exchanges.',
    tags: ['Earrings', 'Lotus', 'Jhumka', 'Teal', 'Sea Green'],
    is_featured: true,
    is_new_arrival: true,
    is_best_seller: true,
    is_active: true,
    images: ['/images/earrings_teal_lotus_jhumka.jpg'],
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'prod-ear-14',
    name: 'AJ Art Royal Lavender Purple Chandbali Statement Earrings',
    sku: 'SRJ-CHND-114',
    slug: 'aj-art-royal-lavender-purple-chandbali-statement-earrings',
    category_id: 'cat-1',
    category_name: 'Earrings',
    description: 'Royal AJ Art designer silver polish lavender purple cabochon gemstone & CZ diamond cluster crescent Chandbali earrings.',
    original_price: 250,
    selling_price: 160,
    discount_percentage: 36,
    stock_quantity: 20,
    low_stock_threshold: 3,
    material: 'Silver Plated Designer Metal',
    stone_type: 'Lavender Purple Gemstones & CZ Diamonds',
    colour: 'Silver & Lavender Purple',
    weight: '42g',
    size: 'Large Chandbali',
    dimensions: '7.5cm Length x 4cm Width',
    care_instructions: 'Store safely in jewellery box.',
    shipping_info: 'Insured Express Shipping in 2-4 business days.',
    return_info: '7-Day Easy Returns & Exchanges.',
    tags: ['Earrings', 'Chandbali', 'Purple', 'Lavender', 'AJ Art'],
    is_featured: true,
    is_new_arrival: true,
    is_best_seller: true,
    is_active: true,
    images: ['/images/earrings_lavender_purple_chandbali.jpg'],
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'prod-ear-15',
    name: 'AJ Art Soft Powder Pink Chandbali Statement Earrings',
    sku: 'SRJ-CHND-115',
    slug: 'aj-art-soft-powder-pink-chandbali-statement-earrings',
    category_id: 'cat-1',
    category_name: 'Earrings',
    description: 'Stunning AJ Art silver finish pastel powder pink gemstone & polki cluster traditional crescent Chandbali earrings.',
    original_price: 250,
    selling_price: 160,
    discount_percentage: 36,
    stock_quantity: 20,
    low_stock_threshold: 3,
    material: 'Silver Plated AJ Art Alloy',
    stone_type: 'Powder Pink Gemstones & CZ Diamonds',
    colour: 'Silver & Powder Pink',
    weight: '41g',
    size: 'Large Chandbali',
    dimensions: '7.4cm Length x 3.9cm Width',
    care_instructions: 'Keep away from direct moisture.',
    shipping_info: 'Insured Express Shipping in 2-4 business days.',
    return_info: '7-Day Easy Returns & Exchanges.',
    tags: ['Earrings', 'Chandbali', 'Pink', 'Powder Pink', 'AJ Art'],
    is_featured: true,
    is_new_arrival: true,
    is_best_seller: true,
    is_active: true,
    images: ['/images/earrings_powder_pink_chandbali.jpg'],
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'prod-ear-16',
    name: 'Laher Deep Violet Purple Lotus Enamel Jhumka Earrings',
    sku: 'SRJ-JHM-116',
    slug: 'laher-deep-violet-purple-lotus-enamel-jhumka-earrings',
    category_id: 'cat-1',
    category_name: 'Earrings',
    description: 'Regal Laher deep violet purple enamel lotus double-tier silver oxide Jhumka earrings with purple crystal bead drops.',
    original_price: 250,
    selling_price: 160,
    discount_percentage: 36,
    stock_quantity: 20,
    low_stock_threshold: 3,
    material: 'Silver Oxide Metal',
    stone_type: 'Violet Purple Enamel & Crystal Beads',
    colour: 'Silver & Deep Violet',
    weight: '33g',
    size: 'Standard Jhumka',
    dimensions: '6.2cm Length x 2.8cm Width',
    care_instructions: 'Keep away from moisture and direct chemical sprays.',
    shipping_info: 'Insured Express Shipping in 2-4 business days.',
    return_info: '7-Day Easy Returns & Exchanges.',
    tags: ['Earrings', 'Lotus', 'Jhumka', 'Violet', 'Purple'],
    is_featured: true,
    is_new_arrival: true,
    is_best_seller: true,
    is_active: true,
    images: ['/images/earrings_violet_lotus_jhumka.png'],
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'prod-ear-17',
    name: 'Laher Refreshing Mint Green Lotus Enamel Jhumka Earrings',
    sku: 'SRJ-JHM-117',
    slug: 'laher-refreshing-mint-green-lotus-enamel-jhumka-earrings',
    category_id: 'cat-1',
    category_name: 'Earrings',
    description: 'Charming Laher mint green enamel lotus motif silver oxide Jhumka earrings with seafoam mint bead drops.',
    original_price: 250,
    selling_price: 160,
    discount_percentage: 36,
    stock_quantity: 20,
    low_stock_threshold: 3,
    material: 'Silver Oxide Finish Metal',
    stone_type: 'Mint Green Enamel & Crystal Beads',
    colour: 'Silver & Mint Green',
    weight: '32g',
    size: 'Standard Jhumka',
    dimensions: '6.1cm Length x 2.8cm Width',
    care_instructions: 'Store in dry cloth pouch after use.',
    shipping_info: 'Insured Express Shipping in 2-4 business days.',
    return_info: '7-Day Easy Returns & Exchanges.',
    tags: ['Earrings', 'Lotus', 'Jhumka', 'Mint Green', 'Green'],
    is_featured: true,
    is_new_arrival: true,
    is_best_seller: true,
    is_active: true,
    images: ['/images/earrings_mint_green_lotus_jhumka.png'],
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'prod-ear-18',
    name: 'Dhara Pastel Lilac Lavender Floral Jhumka Earrings',
    sku: 'SRJ-JHM-118',
    slug: 'dhara-pastel-lilac-lavender-floral-jhumka-earrings',
    category_id: 'cat-1',
    category_name: 'Earrings',
    description: 'Dhara royal collection floral motif pastel lilac lavender cabochon gemstone & CZ diamond studded silver polish Jhumka earrings.',
    original_price: 250,
    selling_price: 160,
    discount_percentage: 36,
    stock_quantity: 20,
    low_stock_threshold: 3,
    material: 'Silver Polish Alloy',
    stone_type: 'Lilac Gemstones & CZ Diamonds',
    colour: 'Silver & Pastel Lilac',
    weight: '34g',
    size: 'Medium Jhumka',
    dimensions: '6.2cm Length x 2.9cm Width',
    care_instructions: 'Keep away from direct moisture.',
    shipping_info: 'Insured Express Shipping in 2-4 business days.',
    return_info: '7-Day Easy Returns & Exchanges.',
    tags: ['Earrings', 'Jhumka', 'Lilac', 'Lavender', 'Dhara'],
    is_featured: true,
    is_new_arrival: true,
    is_best_seller: true,
    is_active: true,
    images: ['/images/earrings_dhara_lilac_jhumka.jpg'],
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'prod-ear-19',
    name: 'Laher Deep Maroon Red Lotus Enamel Jhumka Earrings',
    sku: 'SRJ-JHM-119',
    slug: 'laher-deep-maroon-red-lotus-enamel-jhumka-earrings',
    category_id: 'cat-1',
    category_name: 'Earrings',
    description: 'Traditional Laher deep maroon red enamel lotus double-tier silver oxide Jhumka earrings with ruby red bead drops.',
    original_price: 250,
    selling_price: 160,
    discount_percentage: 36,
    stock_quantity: 20,
    low_stock_threshold: 3,
    material: 'Silver Oxide Metal',
    stone_type: 'Maroon Red Enamel & Crystal Beads',
    colour: 'Silver & Maroon Red',
    weight: '33g',
    size: 'Standard Jhumka',
    dimensions: '6.2cm Length x 2.8cm Width',
    care_instructions: 'Store safely in dry pouch.',
    shipping_info: 'Insured Express Shipping in 2-4 business days.',
    return_info: '7-Day Easy Returns & Exchanges.',
    tags: ['Earrings', 'Lotus', 'Jhumka', 'Maroon', 'Red'],
    is_featured: true,
    is_new_arrival: true,
    is_best_seller: true,
    is_active: true,
    images: ['/images/earrings_maroon_red_lotus_jhumka.jpg'],
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'prod-ear-20',
    name: 'Laher Bright Sunshine Yellow Lotus Enamel Jhumka Earrings',
    sku: 'SRJ-JHM-120',
    slug: 'laher-bright-sunshine-yellow-lotus-enamel-jhumka-earrings',
    category_id: 'cat-1',
    category_name: 'Earrings',
    description: 'Festive Laher bright sunshine yellow enamel lotus motif silver oxide Jhumka earrings with yellow crystal bead drops.',
    original_price: 250,
    selling_price: 160,
    discount_percentage: 36,
    stock_quantity: 20,
    low_stock_threshold: 3,
    material: 'Silver Oxide Finish Metal',
    stone_type: 'Sunshine Yellow Enamel & Crystal Beads',
    colour: 'Silver & Sunshine Yellow',
    weight: '32g',
    size: 'Standard Jhumka',
    dimensions: '6.1cm Length x 2.8cm Width',
    care_instructions: 'Keep away from direct heat and water.',
    shipping_info: 'Insured Express Shipping in 2-4 business days.',
    return_info: '7-Day Easy Returns & Exchanges.',
    tags: ['Earrings', 'Lotus', 'Jhumka', 'Yellow', 'Festive'],
    is_featured: true,
    is_new_arrival: true,
    is_best_seller: true,
    is_active: true,
    images: ['/images/earrings_yellow_lotus_jhumka.png'],
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'prod-ear-21',
    name: 'Dhara Multicolour Rainbow Navratna Jhumka Earrings',
    sku: 'SRJ-JHM-121',
    slug: 'dhara-multicolour-rainbow-navratna-jhumka-earrings',
    category_id: 'cat-1',
    category_name: 'Earrings',
    description: 'Vibrant Dhara floral motif rainbow Navratna multicolour cabochon gemstone & CZ diamond studded silver polish Jhumka earrings.',
    original_price: 250,
    selling_price: 160,
    discount_percentage: 36,
    stock_quantity: 20,
    low_stock_threshold: 3,
    material: 'Silver Polish Alloy',
    stone_type: 'Multicolour Gemstones & CZ Diamonds',
    colour: 'Silver & Rainbow Multicolour',
    weight: '35g',
    size: 'Medium Jhumka',
    dimensions: '6.3cm Length x 3cm Width',
    care_instructions: 'Keep away from moisture and chemical sprays.',
    shipping_info: 'Insured Express Shipping in 2-4 business days.',
    return_info: '7-Day Easy Returns & Exchanges.',
    tags: ['Earrings', 'Jhumka', 'Multicolour', 'Navratna', 'Dhara'],
    is_featured: true,
    is_new_arrival: true,
    is_best_seller: true,
    is_active: true,
    images: ['/images/earrings_dhara_multicolour.png'],
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'prod-ear-22',
    name: 'Laher Soft Pastel Lavender Lotus Enamel Jhumka Earrings',
    sku: 'SRJ-JHM-122',
    slug: 'laher-soft-pastel-lavender-lotus-enamel-jhumka-earrings',
    category_id: 'cat-1',
    category_name: 'Earrings',
    description: 'Enchanting Laher pastel lavender lilac enamel lotus motif silver oxide Jhumka earrings with matching bead drops.',
    original_price: 250,
    selling_price: 160,
    discount_percentage: 36,
    stock_quantity: 20,
    low_stock_threshold: 3,
    material: 'Silver Oxide Finish Metal',
    stone_type: 'Pastel Lavender Enamel & Crystal Beads',
    colour: 'Silver & Pastel Lavender',
    weight: '32g',
    size: 'Standard Jhumka',
    dimensions: '6.1cm Length x 2.8cm Width',
    care_instructions: 'Store safely in dry cloth pouch.',
    shipping_info: 'Insured Express Shipping in 2-4 business days.',
    return_info: '7-Day Easy Returns & Exchanges.',
    tags: ['Earrings', 'Lotus', 'Jhumka', 'Lavender', 'Pastel'],
    is_featured: true,
    is_new_arrival: true,
    is_best_seller: true,
    is_active: true,
    images: ['/images/earrings_laher_lavender_lotus.jpg'],
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'prod-ear-23',
    name: 'Dhara Royal Emerald Green Cabochon Jhumka Earrings',
    sku: 'SRJ-JHM-123',
    slug: 'dhara-royal-emerald-green-cabochon-jhumka-earrings',
    category_id: 'cat-1',
    category_name: 'Earrings',
    description: 'Dhara signature circular emerald green cabochon gemstone & CZ diamond studded silver polish Jhumka earrings with green bead drops.',
    original_price: 250,
    selling_price: 160,
    discount_percentage: 36,
    stock_quantity: 20,
    low_stock_threshold: 3,
    material: 'Silver Polish Premium Alloy',
    stone_type: 'Emerald Green Gemstones & CZ Diamonds',
    colour: 'Silver & Emerald Green',
    weight: '34g',
    size: 'Medium Jhumka',
    dimensions: '6.2cm Length x 2.9cm Width',
    care_instructions: 'Keep away from direct heat and water.',
    shipping_info: 'Insured Express Shipping in 2-4 business days.',
    return_info: '7-Day Easy Returns & Exchanges.',
    tags: ['Earrings', 'Jhumka', 'Emerald', 'Green', 'Dhara'],
    is_featured: true,
    is_new_arrival: true,
    is_best_seller: true,
    is_active: true,
    images: ['/images/earrings_dhara_emerald_green.png'],
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'prod-ear-24',
    name: 'Dhara Peach Coral Floral Gemstone Jhumka Earrings',
    sku: 'SRJ-JHM-124',
    slug: 'dhara-peach-coral-floral-gemstone-jhumka-earrings',
    category_id: 'cat-1',
    category_name: 'Earrings',
    description: 'Elegant Dhara floral motif peach coral cabochon gemstone & CZ diamond cluster silver polish Jhumka earrings.',
    original_price: 250,
    selling_price: 160,
    discount_percentage: 36,
    stock_quantity: 20,
    low_stock_threshold: 3,
    material: 'Silver Polish Alloy',
    stone_type: 'Peach Coral Gemstones & CZ Diamonds',
    colour: 'Silver & Peach Coral',
    weight: '34g',
    size: 'Medium Jhumka',
    dimensions: '6.2cm Length x 2.9cm Width',
    care_instructions: 'Clean with dry soft cloth after use.',
    shipping_info: 'Insured Express Shipping in 2-4 business days.',
    return_info: '7-Day Easy Returns & Exchanges.',
    tags: ['Earrings', 'Jhumka', 'Peach', 'Coral', 'Dhara'],
    is_featured: true,
    is_new_arrival: true,
    is_best_seller: true,
    is_active: true,
    images: ['/images/earrings_dhara_peach_coral.jpg'],
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'prod-ear-25',
    name: 'Dhara Soft Rose Pink Circular Gemstone Jhumka Earrings',
    sku: 'SRJ-JHM-125',
    slug: 'dhara-soft-rose-pink-circular-gemstone-jhumka-earrings',
    category_id: 'cat-1',
    category_name: 'Earrings',
    description: 'Captivating Dhara circular rose pink cabochon gemstone & CZ diamond studded silver polish Jhumka earrings with pink bead drops.',
    original_price: 250,
    selling_price: 160,
    discount_percentage: 36,
    stock_quantity: 20,
    low_stock_threshold: 3,
    material: 'Silver Polish Premium Alloy',
    stone_type: 'Rose Pink Gemstones & CZ Diamonds',
    colour: 'Silver & Rose Pink',
    weight: '34g',
    size: 'Medium Jhumka',
    dimensions: '6.2cm Length x 2.9cm Width',
    care_instructions: 'Store in dry airtight pouch.',
    shipping_info: 'Insured Express Shipping in 2-4 business days.',
    return_info: '7-Day Easy Returns & Exchanges.',
    tags: ['Earrings', 'Jhumka', 'Pink', 'Rose Pink', 'Dhara'],
    is_featured: true,
    is_new_arrival: true,
    is_best_seller: true,
    is_active: true,
    images: ['/images/earrings_dhara_rose_pink.jpg'],
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'prod-ear-26',
    name: 'Laher Midnight Jet Black Lotus Enamel Jhumka Earrings',
    sku: 'SRJ-JHM-126',
    slug: 'laher-midnight-jet-black-lotus-enamel-jhumka-earrings',
    category_id: 'cat-1',
    category_name: 'Earrings',
    description: 'Chic Laher midnight jet black enamel lotus double-tier silver oxide Jhumka earrings with black crystal bead drops.',
    original_price: 250,
    selling_price: 160,
    discount_percentage: 36,
    stock_quantity: 20,
    low_stock_threshold: 3,
    material: 'Silver Oxide Metal',
    stone_type: 'Jet Black Enamel & Crystal Beads',
    colour: 'Silver & Jet Black',
    weight: '33g',
    size: 'Standard Jhumka',
    dimensions: '6.2cm Length x 2.8cm Width',
    care_instructions: 'Keep away from moisture and direct chemical sprays.',
    shipping_info: 'Insured Express Shipping in 2-4 business days.',
    return_info: '7-Day Easy Returns & Exchanges.',
    tags: ['Earrings', 'Lotus', 'Jhumka', 'Black', 'Jet Black'],
    is_featured: true,
    is_new_arrival: true,
    is_best_seller: true,
    is_active: true,
    images: ['/images/earrings_black_lotus_jhumka.png'],
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'prod-ear-27',
    name: 'Dhara Royal Emerald Green Floral Gemstone Jhumka Earrings',
    sku: 'SRJ-JHM-127',
    slug: 'dhara-royal-emerald-green-floral-gemstone-jhumka-earrings',
    category_id: 'cat-1',
    category_name: 'Earrings',
    description: 'Dhara signature floral motif emerald green cabochon gemstone & CZ diamond studded silver polish Jhumka earrings.',
    original_price: 250,
    selling_price: 160,
    discount_percentage: 36,
    stock_quantity: 20,
    low_stock_threshold: 3,
    material: 'Silver Polish Premium Alloy',
    stone_type: 'Emerald Green Gemstones & CZ Diamonds',
    colour: 'Silver & Emerald Green',
    weight: '34g',
    size: 'Medium Jhumka',
    dimensions: '6.2cm Length x 2.9cm Width',
    care_instructions: 'Store in dry airtight pouch.',
    shipping_info: 'Insured Express Shipping in 2-4 business days.',
    return_info: '7-Day Easy Returns & Exchanges.',
    tags: ['Earrings', 'Jhumka', 'Emerald', 'Green', 'Dhara'],
    is_featured: true,
    is_new_arrival: true,
    is_best_seller: true,
    is_active: true,
    images: ['/images/earrings_dhara_emerald_floral_jhumka.jpg'],
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
];

export const INITIAL_CUSTOMERS: UserProfile[] = [
  {
    id: 'cust-admin',
    email: 'sushmitha.admin@srjewellery.com',
    full_name: 'Sushmitha Admin',
    phone: '+91 98765 43210',
    role: 'ADMIN',
    created_at: '2024-01-01T00:00:00.000Z',
  },
];

export const INITIAL_CUSTOMER_ADDRESSES: CustomerAddress[] = [];

export const INITIAL_ORDERS: Order[] = [];

export const INITIAL_PAYMENTS: PaymentTransaction[] = [];

export const INITIAL_CONTACT_MESSAGES: ContactMessage[] = [];

export const INITIAL_INVENTORY_HISTORY: InventoryHistory[] = [];

export const INITIAL_ACTIVITY_LOGS: AdminActivityLog[] = [
  {
    id: 'log-init',
    admin_id: 'cust-admin',
    admin_name: 'Sushmitha Admin',
    action: 'STORE_RESET',
    entity_type: 'STORE',
    entity_id: '00000000-0000-0000-0000-000000000001',
    description: 'Store database reset for fresh product additions and order processing.',
    created_at: '2024-01-01T00:00:00.000Z',
  },
];

export const INITIAL_CUSTOMER_NOTES: CustomerNote[] = [];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'coup-uday99',
    code: 'UDAY99',
    discount_type: 'PERCENTAGE',
    discount_value: 99,
    min_order_amount: 0,
    max_discount_amount: 0,
    status: 'ACTIVE',
    usage_count: 99,
    created_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'coup-1',
    code: 'WELCOME10',
    discount_type: 'PERCENTAGE',
    discount_value: 10,
    min_order_amount: 999,
    status: 'ACTIVE',
    usage_count: 24,
    created_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'coup-2',
    code: 'ROYAL500',
    discount_type: 'FLAT',
    discount_value: 500,
    min_order_amount: 4999,
    status: 'ACTIVE',
    usage_count: 12,
    created_at: '2024-01-01T00:00:00.000Z',
  },
];

export const INITIAL_REVIEWS: any[] = [
  {
    id: 'rev-1',
    product_id: 'prod-1',
    product_name: 'Royal Kundan & Pearl Bridal Choker Set',
    customer_name: 'Ananya Sharma',
    customer_email: 'ananya.sharma@example.com',
    rating: 5,
    title: 'Exquisite craftsmanship & royal finish!',
    comment: 'The choker set looks even more breathtaking in person. The gold polishing and freshwater pearls are premium quality!',
    status: 'APPROVED',
    created_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'rev-2',
    product_id: 'prod-2',
    product_name: 'Antique Gold Plated Jhumka Earrings',
    customer_name: 'Priya Patel',
    customer_email: 'priya.patel@example.com',
    rating: 5,
    title: 'Perfect weight and traditional look',
    comment: 'Wore these for a family wedding and received endless compliments! Light on the ears and very elegant.',
    status: 'APPROVED',
    created_at: '2024-01-01T00:00:00.000Z',
  },
];
